dscpesu/my-first-opensource-contribution

my-first-opensource-contribution/app/hackfest/page.js
my-first-opensource-contribution/app/page.js

fixed link and centering issues

minor fixes @Lehar

---

my-first-opensource-contribution/contributions/anirudhprasad.mdx

- Added mdx file for user Icarus131

docs: added mdx file

---

my-first-opensource-contribution/contributions/adithya-s-k.mdx

closing issue #14 
I have added adithya-s-k markdown here is a screenshot

added adithya markdown file - Adithya S K

---

my-first-opensource-contribution/contributions/vasanth.mdx

Added Vasanth's markdown file - Vasanth

---

my-first-opensource-contribution/contributions/chandana-m-s.mdx

Closing issue #26
Created mdx file

Added chandana-m-s markdown file     Chandana M S

---

my-first-opensource-contribution/contributions/furqaan.mdx

closing issue #35 
Added a markdown file

added mohammed furqaan mkdn file - Furqaan #35

---

my-first-opensource-contribution/contributions/hamza.mdx

closing issue #32
added markdown for Hamza.

added markdown for Hamza

---

my-first-opensource-contribution/contributions/bhavanabandi.mdx

closing issue #18 
Please add my markdown

Added bhavanabandi markdown - Bhavana Bandi

---

my-first-opensource-contribution/contributions/Leharaditya.mdx

added Leharaditya.mdx @Lehar

---

my-first-opensource-contribution/contributions/m-s-varun.mdx

Added Varun's mdx file

---

my-first-opensource-contribution/contributions/anirudhprasad.mdx

docs: modified anirudhprasad.mdx

---

my-first-opensource-contribution/contributions/ganeshv.mdx

closing issue #37 
This creates a markdown file with my profile information.

Pull request 

---

my-first-opensource-contribution/app/Components/Introduction.jsx

added conditional 'a' / 'an' for the role in contribution

added conditional rendering @Lehar

---

my-first-opensource-contribution/contributions/avanishshenoy.mdx

Add Avanish Shenoy markdown file

---

my-first-opensource-contribution/contributions/anirudh-h-a.mdx

I have added Anirudh H As Markdown File

Added Anirudh's markdown file

---

my-first-opensource-contribution/contributions/chandana-m-s.mdx

Closing issue #78 
Updated mdx file

Updated chandana-m-s markdown file

---

Surabhi-KC.md

closing issue #44 
I have added my markdown file to the cloned repository

Added markdown file

---

my-first-opensource-contribution/contributions/sakethvunka.mdx

sakethvunka.mdx

---

my-first-opensource-contribution/contributions/sharath-m-s.mdx

closing issue #28 
I have added sharath-m-s markdown.
Github user: Sharath-44
email: sharath.shashidhara@gmail.com

added sharath-m-s markdown file - Sharath M S

---

my-first-opensource-contribution/contributions/nehasundararaman.mdx

closing issue #30 
please review and add my markdown file.

Neha's markdown

---

my-first-opensource-contribution/contributions/swamy.mdx

Added ananth's markdown file

---

my-first-opensource-contribution/contributions/supratikvishnu.mdx

closing issue #19 
I am done adding my mdx file for the website

added Supratik's markdown

---

my-first-opensource-contribution/contributions/anuraag_srivatsa.mdx

Closed issue #38 
Added Personal Markdown Page

Added personal Markdown - Anuraag 

---

my-first-opensource-contribution/contributions/ankit-avinash.mdx

closing issue #24 
I have added markdown file.

added ankit avinash mkdn file - Ankit Avinash

---

my-first-opensource-contribution/contributions/Bhvaeen_Madhavan.mdx

closing issue #41 
i have added Bhaveen Madhavan's markdown

Added Bhaveen's markdown file

---

my-first-opensource-contribution/contributions/Abhigna-D.mdx

feat: adding Abhigna-D.mdx

---

my-first-opensource-contribution/contributions/Aditi-P-Acharya.mdx

feat: adding Aditi-P-Acharya.mdx

---

my-first-opensource-contribution/contributions/Akib-Vijapura.mdx

Add Akib-Vijapura's Profile
Fixes : #118

Feat: Add Akib-Vijapura's Profile

---

my-first-opensource-contribution/contributions/Sairam-S.mdx

added Sairam markdown

---

my-first-opensource-contribution/contributions/Vishnu-Chiyedu.mdx

I added a markup file about myself

Made My Markup File - Vishnu Chiyedu

---

my-first-opensource-contribution/contributions/tejaskumar_reddy_j.mdx

Made My Changes In Markup File Succesfully

Made My Changes in Markup File - Tejaskumar Reddy J

---

my-first-opensource-contribution/contributions/Shanker-Singh.mdx

added Shanker-Singh.mdx file

---

my-first-opensource-contribution/contributions/mythi-p-r.mdx

added Mythri markdown file

---

my-first-opensource-contribution/contributions/sandeshkumatgi.mdx

Added personal markdown

---

my-first-opensource-contribution/contributions/samay-sr.mdx

added samay-sr.mdx

---

my-first-opensource-contribution/contributions/sarthaks55.mdx

Added sarthaks55.mdx file

---

my-first-opensource-contribution/contributions/Jayant-Anand.mdx

Add Jayant's mdx file

---

my-first-opensource-contribution/contributions/Janani.mdx

added janani mdx file

---

my-first-opensource-contribution/contributions/bcsamrudh.mdx

added bcsamrudh mdx

---

my-first-opensource-contribution/contributions/sourabh-rk.mdx
my-first-opensource-contribution/contributions/sourabh.mdx

Added Sourabh markdown

---

my-first-opensource-contribution/contributions/deeksha-h-m.mdx

#285
Added a personal markdown file.

added deeksha-h-m mdx

---

my-first-opensource-contribution/contributions/chandana-b-s.mdx

#262
Added a personal markdown file

added chandana-b-s mdx

---

my-first-opensource-contribution/contributions/SrihariIyer.mdx

new file: Added Srihari Iyer Markdown

---

my-first-opensource-contribution/contributions/nikhiljohns.mdx

Added Markdown Profile

---

my-first-opensource-contribution/contributions/karan-jadhav.mdx

added Karan-jadhav mdx

---

my-first-opensource-contribution/contributions/divya-eshwar.mdx

added divya-eshwar.mdx

---

my-first-opensource-contribution/contributions/sathyajitp.mdx

added my information into the file

added sathyajitp mdx file

---

my-first-opensource-contribution/contributions/vedant-varma.mdx

I added my mdx file and created the pull request

added vedant-varma mdx

---

my-first-opensource-contribution/contributions/varsha-badri.mdx

add varsha-badri mdx

---

my-first-opensource-contribution/contributions/desai-vaishnavi-reddy.mdx

added desai-vaishnavi-reddy.mdx

added desai-vaishnavi-reddy.mdx

---

my-first-opensource-contribution/contributions/vismaya-m.mdx

added vismaya.mdx

---

my-first-opensource-contribution/contributions/nishant-k-holla.mdx

Add nishant-k-holla.mdx

---

my-first-opensource-contribution/contributions/deeksha-j.mdx

Added deeksha-j.mdx

---

my-first-opensource-contribution/contributions/chandana-s.mdx

adding chandanas mdx file

---

my-first-opensource-contribution/contributions/S_P_Suhas.mdx

added S-P-Suhas.mdx

---

my-first-opensource-contribution/contributions/deeksha-r.mdx

added deeksha-r.mdx

---

my-first-opensource-contribution/contributions/anika.mdx

Solved issue #111 
I have created a new MDX file in which I have given details regarding my Experience, Projects and Socials.

added anika.mdx

---

my-first-opensource-contribution/contributions/SuryaSatvik.mdx

added my SuryaSatvik mdx 

---

my-first-opensource-contribution/contributions/Arundhati-Sitharam.mdx

Markdown_aru_added mdx

---

my-first-opensource-contribution/contributions/kshitijkale.mdx

add kshitijkale.mdx

---

my-first-opensource-contribution/contributions/Sanjeev-R-Rao.mdx

Added Sanjeev-R_Rao 

---

my-first-opensource-contribution/contributions/manu-narayan-hegde.mdx

added manu-narayan-hegde markdown file

added manu-narayan-hegde markdown file

---

my-first-opensource-contribution/contributions/ritika-s.mdx

Added ritika-s.mdx

---

my-first-opensource-contribution/contributions/vasnitha_d.mdx

added vasnitha_d.mdx

---

my-first-opensource-contribution/contributions/sanjanabj.mdx

I made a markdown file

---

my-first-opensource-contribution/contributions/ullas-g.mdx

added Ullas-g mdx

---

my-first-opensource-contribution/contributions/k-srinivasa-ankita.mdx

added k-srinivasa-ankita mdx

---

my-first-opensource-contribution/contributions/nishant-k-holla.mdx

Fix linkedin link in nishant-k-holla.mdx

---

my-first-opensource-contribution/contributions/Akshay-Hegde.mdx

email-(hegdeakshay2004@gmail.com)

added markdown file Akshay-Hegde

---

my-first-opensource-contribution/contributions/grass.mdx

Add Shailja S MArkdown file called grass.mdx

Add Shailja S Markdown

---

my-first-opensource-contribution/contributions/SrihariIyer.mdx

Just a few minor tweaks to the markdown file.

New Change Committed.

---

my-first-opensource-contribution/contributions/Lekhya.mdx

This reverts commit 19b41c0c85a426ff0610cd3739b48b5553ad6f92.

Revert "chore: updated Lekhya.mdx file (#654)"
